stages:
  - build

# Variables that should be specified from the project settings:
# - ENABLE_JOBS         : list of jobs to run, such as "build-linux,build-windows"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-linux:
  stage: build
  tags:
    - os/linux
  rules:
    - if: '$ENABLE_JOBS =~ /build-linux/'
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j

build-windows:
  stage: build
  tags:
    - os/win11
  rules:
    - if: '$ENABLE_JOBS =~ /build-windows/'
  parallel:
    matrix:
      - BUILD_TYPE: ['Release', 'Debug']
        CUDA: 'ON'
        DX12: 'ON'
        VULKAN: 'ON'
        SHADERS: 'ON'
      - BUILD_TYPE: 'Release'
        CUDA: 'OFF'
        DX12: 'ON'
        VULKAN: 'ON'
        SHADERS: 'ON'
      - BUILD_TYPE: 'Release'
        CUDA: 'ON'
        DX12: 'OFF'
        VULKAN: 'ON'
        SHADERS: 'ON'
      - BUILD_TYPE: 'Release'
        CUDA: 'ON'
        DX12: 'ON'
        VULKAN: 'OFF'
        SHADERS: 'ON'
      - BUILD_TYPE: 'Release'
        CUDA: 'ON'
        DX12: 'ON'
        VULKAN: 'ON'
        SHADERS: 'OFF'
  script:
    - tools/set_vs_vars.ps1
    - $env:PATH += ";$CI_PROJECT_DIR/external"
    - mkdir build
    - cd build
    - cmake .. -GNinja "-DCMAKE_BUILD_TYPE=$BUILD_TYPE" "-DNTC_WITH_CUDA=$CUDA" "-DNTC_WITH_DX12=$DX12" "-DNTC_WITH_VULKAN=$VULKAN" "-DNTC_WITH_PREBUILT_SHADERS=$SHADERS"
    - ninja
